#ifndef CONFIG_H
#define CONFIG_H

// #define BLYNK_TEMPLATE_ID   "YOUR_TEMPLATE_ID"
// #define BLYNK_TEMPLATE_NAME "YOUR_TEMPLATE_NAME"
// #define BLYNK_AUTH          "YOUR_BLYNK_AUTH_TOKEN"

// #define WIFI_SSID           "YOUR_WIFI_SSID"
// #define WIFI_PASS           "YOUR_WIFI_PASS"

#define BLYNK_TEMPLATE_ID   "YOUR_TEMPLATE_ID"
#define BLYNK_TEMPLATE_NAME "YOUR_TEMPLATE_NAME"
#define BLYNK_AUTH          "YOUR_BLYNK_AUTH_TOKEN"

#define WIFI_SSID           "YOUR_WIFI_SSID"
#define WIFI_PASS           "YOUR_WIFI_PASS"

#endif